name: Build android package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y make openjdk-8-jdk openjdk-8-jre ant-contrib python3-requests python3-pip
          sudo pip3 install websocket-client

          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://gitlab.com/".insteadOf "git@gitlab.com:"

          git clone --depth 1 --recurse-submodules https://github.com/nillerusr/srceng-android.git /tmp/upstream
          mkdir -p jni/src
          cp -r /tmp/upstream/jni/src/tierhook jni/src/

          git clone --depth 1 https://gitlab.com/LostGamer/ndk-binaries
          git clone --depth 1 https://gitlab.com/LostGamer/android-sdk
          git clone --depth 1 https://github.com/nillerusr/srcsdk.git
          cd srcsdk
          git submodule update --init --recursive || true
          cd ../

          DEPLOY_BRANCH=srceng-old-port COMMIT=$(git rev-parse HEAD) scripts/workflow.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            bin/*
